"""create initial tables

Revision ID: bb385675a8f7
Revises: 
Create Date: 2026-03-28 16:07:16.831971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb385675a8f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^UI[A-Za-z0-9]{7}$'", name='ck_employees_id_format'),
    sa.CheckConstraint("phone_number ~ '^[89][0-9]{7}$'", name='ck_employees_phone_number_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('cafe_employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cafe_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=9), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id', 'employee_id', name='uq_cafe_employees_cafe_employee')
    )
    op.create_index('ix_cafe_employees_cafe_id', 'cafe_employees', ['cafe_id'], unique=False)
    op.create_index('ix_cafe_employees_employee_id', 'cafe_employees', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cafe_employees_employee_id', table_name='cafe_employees')
    op.drop_index('ix_cafe_employees_cafe_id', table_name='cafe_employees')
    op.drop_table('cafe_employees')
    op.drop_table('employees')
    op.drop_table('cafes')
    # ### end Alembic commands ###
